# Generated by Django 5.1.7 on 2025-03-18 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('flight', 'BY FLIGHT'), ('train', 'BY TRAIN')], max_length=20)),
                ('start_location', models.CharField(max_length=50)),
                ('end_location', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_travel', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_travel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ManyToManyField(related_name='projects', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
