# Generated by Django 4.2.15 on 2025-03-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_travel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='Project Description', max_length=255),
            preserve_default=False,
        ),
    ]
